<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\src\CloudNativeKit.Caching\CloudNativeKit.Caching.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\src\CloudNativeKit.Core\CloudNativeKit.Core.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\src\CloudNativeKit.Integration.Wolverine\CloudNativeKit.Integration.Wolverine.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\src\CloudNativeKit.SerilogLogging\CloudNativeKit.SerilogLogging.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\src\CloudNativeKit.Persistence.EfCore.Postgres\CloudNativeKit.Persistence.EfCore.Postgres.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\src\CloudNativeKit.Persistence.Mongo\CloudNativeKit.Persistence.Mongo.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\src\CloudNativeKit.Security\CloudNativeKit.Security.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\src\CloudNativeKit.Web\CloudNativeKit.Web.csproj" />
  </ItemGroup>

  <ItemGroup Label="XUnit">
    <PackageReference Include="xunit.v3.assert" />
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Extensions.Logging.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Testcontainers.MongoDb" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="WebMotions.Fake.Authentication.JwtBearer" />
    <PackageReference Include="WireMock.Net" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentAssertions.Web" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="AutoBogus" />
    <PackageReference Include="AutoBogus.NSubstitute" />
    <PackageReference Include="Hypothesist" />
  </ItemGroup>

</Project>
