# https://github.com/fuxingloh/multi-labeler
# https://stackoverflow.com/questions/58899999/regexp-to-match-conventional-commit-syntax
version: v1

labels:
- label: "feature"
  matcher:
    title: '/^(feat)(\([a-z ]+\))?: .+/'
    commits: '/^(feat)(\([a-z ]+\))?: .+/'
    branch: '/^(feat)(\([a-z ]+\))?\/.+/'

- label: "bug"
  matcher:
    title: '/^(fix)(\([a-z ]+\))?: .+/'
    commits: '/^(fix)(\([a-z ]+\))?: .+/'
    branch: '/^(fix)(\([a-z ]+\))?\/.+/'

- label: "chore"
  matcher:
    title: '/^(chore)(\([a-z ]+\))?: .+/'
    commits: '/^(chore)(\([a-z ]+\))?: .+/'
    branch: '/^(chore)(\([a-z ]+\))?\/.+/'

- label: "documentation"
  matcher:
    title: '/^(docs)(\([a-z ]+\))?: .+/'
    commits: '/^(docs)(\([a-z ]+\))?: .+/'
    branch: '/^(docs)(\([a-z ]+\))?\/.+/'

- label: "devops"
  matcher:
    title: '/^(ci)(\([a-z ]+\))?: .+/'
    commits: '/^(ci)(\([a-z ]+\))?: .+/'
    branch: '/^(ci)(\([a-z ]+\))?\/.+/'

- label: "ci-cd"
  matcher:
    title: '/^(ci)(\([a-z ]+\))?: .+/'
    commits: '/^(ci)(\([a-z ]+\))?: .+/'
    branch: '/^(ci)(\([a-z ]+\))?\/.+/'

- label: "enhancement"
  matcher:
    title: '/^(refactor)(\([a-z ]+\))?: .+/'
    commits: '/^(refactor)(\([a-z ]+\))?: .+/'
    branch: '/^(refactor)(\([a-z ]+\))?\/.+/'

- label: "style"
  matcher:
    title: '/^(style)(\([a-z ]+\))?: .+/'
    commits: '/^(style)(\([a-z ]+\))?: .+/'
    branch: '/^(style)(\([a-z ]+\))?\/.+/'

- label: "performance"
  matcher:
    title: '/^(perf)(\([a-z ]+\))?: .+/'
    commits: '/^(perf)(\([a-z ]+\))?: .+/'
    branch: '/^(perf)(\([a-z ]+\))?\/.+/'

- label: "build"
  matcher:
    title: '/^(build)(\([a-z ]+\))?: .+/'
    commits: '/^(build)(\([a-z ]+\))?: .+/'
    branch: '/^(build)(\([a-z ]+\))?\/.+/'

- label: "test"
  matcher:
    title: '/^(test)(\([a-z ]+\))?: .+/'
    commits: '/^(test)(\([a-z ]+\))?: .+/'
    branch: '/^(test)(\([a-z ]+\))?\/.+/'

- label: "dependencies"
  matcher:
    title: '/^(build)(\([a-z ]+\))?: .+/'
    commits: '/^(build)(\([a-z ]+\))?: .+/'
    branch: '/^(build)(\([a-z ]+\))?\/.+/'

- label: "minor"
  matcher:
    title: '/^(feat)(\([a-z ]+\))?: .+/'
    commits: '/^(feat)(\([a-z ]+\))?: .+/'
    branch: '/^(feat)(\([a-z ]+\))?\/.+/'

- label: "patch"
  matcher:
    title: '/^(fix)(\([a-z ]+\))?: .+/'
    commits: '/^(fix)(\([a-z ]+\))?: .+/'
    branch: '/^(fix)(\([a-z ]+\))?\/.+/'
