<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Services\Catalogs\FoodDelivery.Services.Catalogs.Api\FoodDelivery.Services.Catalogs.Api.csproj" />
    <ProjectReference Include="..\..\..\Shared\Tests.Shared\Tests.Shared.csproj" />
  </ItemGroup>

</Project>
