<Project Sdk="Microsoft.NET.Sdk">

  <!--  https://github.com/dotnet/core/issues/907-->
  <PropertyGroup>
    <WarningsAsErrors></WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Tests.Shared\Tests.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
