<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FoodDelivery.Services.Identity.TestShared\FoodDelivery.Services.Identity.TestShared.csproj" />
  </ItemGroup>

  <!--  Copy appsetings files to test projects for reading from ConfigutationBuilder directly-->
  <!--  https://stackoverflow.com/questions/39791634/read-appsettings-json-values-in-net-core-test-project-->
  <ItemGroup>
    <Content Include="..\..\..\..\src\Services\Identity\FoodDelivery.Services.Identity.Api\appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\..\src\Services\Identity\FoodDelivery.Services.Identity.Api\appsettings.test.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
