<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FoodDelivery.Services.Identity.TestShared\FoodDelivery.Services.Identity.TestShared.csproj" />
  </ItemGroup>

</Project>
