#https://tymisko.hashnode.dev/developing-aspnet-core-apps-in-docker-live-recompilation

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS builder

WORKDIR /src

COPY ./.editorconfig ./
COPY ./nuget.config ./
COPY ./global.json ./

COPY ./src/Directory.Build.props ./
COPY ./src/Directory.Build.targets ./
COPY ./src/Directory.Packages.props ./
COPY ./src/Packages.props ./
COPY ./src/Services/Catalogs/Directory.Build.props ./Services/Catalogs/
        
# TODO: Using wildcard to copy all files in the directory.
COPY ./src/BuildingBlocks/src/CloudNativeKit.Abstractions/CloudNativeKit.Abstractions.csproj ./BuildingBlocks/src/CloudNativeKit.Abstractions/
COPY ./src/BuildingBlocks/src/CloudNativeKit.Core/CloudNativeKit.Core.csproj ./BuildingBlocks/src/CloudNativeKit.Core/
COPY ./src/BuildingBlocks/src/CloudNativeKit.HealthCheck/CloudNativeKit.HealthCheck.csproj ./BuildingBlocks/src/CloudNativeKit.HealthCheck/
COPY ./src/BuildingBlocks/src/CloudNativeKit.OpenTelemetry/CloudNativeKit.OpenTelemetry.csproj ./BuildingBlocks/src/CloudNativeKit.OpenTelemetry/
COPY ./src/BuildingBlocks/src/CloudNativeKit.Resiliency/CloudNativeKit.Resiliency.csproj ./BuildingBlocks/src/CloudNativeKit.Resiliency/
COPY ./src/BuildingBlocks/src/CloudNativeKit.Web/CloudNativeKit.Web.csproj ./BuildingBlocks/src/CloudNativeKit.Web/
COPY ./src/BuildingBlocks/src/CloudNativeKit.Caching/CloudNativeKit.Caching.csproj ./BuildingBlocks/src/CloudNativeKit.Caching/
COPY ./src/BuildingBlocks/src/CloudNativeKit.Email/CloudNativeKit.Email.csproj ./BuildingBlocks/src/CloudNativeKit.Email/
COPY ./src/BuildingBlocks/src/CloudNativeKit.Integration.Wolverine/CloudNativeKit.Integration.Wolverine.csproj ./BuildingBlocks/src/CloudNativeKit.Integration.Wolverine/
COPY ./src/BuildingBlocks/src/CloudNativeKit.OpenApi/CloudNativeKit.OpenApi.csproj ./BuildingBlocks/src/CloudNativeKit.OpenApi/
COPY ./src/BuildingBlocks/src/CloudNativeKit.Persistence.EfCore.Postgres/CloudNativeKit.Persistence.EfCore.Postgres.csproj ./BuildingBlocks/src/CloudNativeKit.Persistence.EfCore.Postgres/
COPY ./src/BuildingBlocks/src/CloudNativeKit.Persistence.Mongo/CloudNativeKit.Persistence.Mongo.csproj ./BuildingBlocks/src/CloudNativeKit.Persistence.Mongo/
COPY ./src/BuildingBlocks/src/CloudNativeKit.SerilogLogging/CloudNativeKit.SerilogLogging.csproj ./BuildingBlocks/src/CloudNativeKit.SerilogLogging/
COPY ./src/BuildingBlocks/src/CloudNativeKit.Validation/CloudNativeKit.Validation.csproj ./BuildingBlocks/src/CloudNativeKit.Validation/

# Copy project files
COPY ./src/BuildingBlocks/ ./BuildingBlocks/
COPY ./src/Services/Catalogs/FoodDelivery.Services.Catalogs.Api/  ./Services/Catalogs/FoodDelivery.Services.Catalogs.Api/
COPY ./src/Services/Catalogs/FoodDelivery.Services.Catalogs/  ./Services/Catalogs/FoodDelivery.Services.Catalogs/
COPY ./src/Services/Shared/  ./Services/Shared/

WORKDIR /src/Services/Catalogs/FoodDelivery.Services.Catalogs.Api/

# https://learn.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-7.0#dotnet-watch-configuration
# https://learn.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-3.1#watch-for-changes
# https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch?WT.mc_id=DOP-MVP-5001942#environment-variables
# Some file systems, such as Docker containers and network shares, may not reliably send change notifications. Set the DOTNET_USE_POLLING_FILE_WATCHER environment variable to 1 or true to poll the file system for changes every four seconds
# If set to "1" or "true", dotnet watch uses a polling file watcher instead of CoreFx's FileSystemWatcher. Used when watching files on network shares or Docker mounted volumes.
ENV DOTNET_USE_POLLING_FILE_WATCHER 1

RUN dotnet watch run  FoodDelivery.Services.Catalogs.Api.csproj --launch-profile Catalogs.Api.LiveRecompilation -p:SkipVersion=true
