using ECommerce.Services.Customers.RestockSubscriptions.Dtos;

namespace ECommerce.Services.Customers.RestockSubscriptions.Features.CreatingRestockSubscription.v1;

public record CreateRestockSubscriptionResponse(RestockSubscriptionDto RestockSubscription);
