<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Aspire\FoodDelivery.ServiceDefaults\FoodDelivery.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.Caching\CloudNativeKit.Caching.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.Email\CloudNativeKit.Email.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.Integration.Wolverine\CloudNativeKit.Integration.Wolverine.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.OpenApi\CloudNativeKit.OpenApi.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.Persistence.EfCore.Postgres\CloudNativeKit.Persistence.EfCore.Postgres.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.Persistence.Mongo\CloudNativeKit.Persistence.Mongo.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.SerilogLogging\CloudNativeKit.SerilogLogging.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.Validation\CloudNativeKit.Validation.csproj" />
    <ProjectReference Include="..\..\Shared\FoodDelivery.Services.Shared\FoodDelivery.Services.Shared.csproj" />
  </ItemGroup>

  <!-- Copy appsetings files to test projects for reading from ConfigutationBuilder directly-->
  <!--Set CopyToPublishDirectory to always for ensuring copy to publish directory and prevent to conflict with other appsentigs.json, if don't set this it is possible other refrence project setting ovverid its own settings in publish dir-->
  <ItemGroup>
    <Content Include="..\FoodDelivery.Services.Orders.Api\appsettings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FoodDelivery.Services.Orders.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.SourceGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
