<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks.Core\BuildingBlocks.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  
  <ItemGroup Label="Health Check">
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="AspNetCore.HealthChecks.MongoDb" />
  </ItemGroup>
  
  <ItemGroup Label="Aspire Packages">
    <PackageReference Include="Aspire.MongoDB.Driver.v3" />
  </ItemGroup>

</Project>
