### implicit-flow-client
GET {{identity_api}}/connect/authorize?
    client_id=spa&
    redirect_uri={{implicit_redirect_uri}}&
    response_type=token&
    scope={{implicit_scope}}&
    state={{auth_state}}
#################################################################
### PKCE Client
### Step 1: Authorize - Get Authorization Code
# code_challenge is base64url(SHA256("code_verifier")) - https://oidcdebugger.com
GET {{identity_api}}/connect/authorize?
    client_id={{pkce_clientId}}&
    redirect_uri={{pkce_redirect_uri}}&
    response_type=code&
    scope={{pkce_scope}}&
    state={{auth_state}}&
    code_challenge={{pkce_code_challenge}}&
    code_challenge_method={{code_challenge_method}}

### Step 2: Token Exchange - Get Access Token
# code is CODE_FROM_URL
POST {{identity_api}}/connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{pkce_clientId}}&
grant_type=authorization_code&
client_secret={{pkce_secret}}&
code={{pkce_auth_code}}&
redirect_uri={{pkce_redirect_uri}}&
code_verifier={{pkce_code_verifier}}

##################################################################