<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.Core\CloudNativeKit.Core.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.HealthCheck\CloudNativeKit.HealthCheck.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.OpenTelemetry\CloudNativeKit.OpenTelemetry.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.Resiliency\CloudNativeKit.Resiliency.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\CloudNativeKit.Web\CloudNativeKit.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
  </ItemGroup>
  
</Project>
