name: Detect Version

on:
  workflow_call:
    inputs:
      publish-production:
        description: "Whether to publish to production (workflow_dispatch only)"
        type: boolean
        required: false
        default: false
    outputs:
      environment:
        description: "The detected environment (production/staging/develop)"
        value: ${{ jobs.detect-environment.outputs.environment }}

jobs:
  detect-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.detect.outputs.environment }}
      image-suffix: ${{ steps.detect.outputs.image-suffix }}
    steps:
      - name: Detect environment
        id: detect
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.publish-production }}" == "true" ]]; then
            echo environment is 'production'
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "image-suffix=" >> $GITHUB_OUTPUT
          elif [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            echo environment is 'staging'
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "image-suffix=staging" >> $GITHUB_OUTPUT
          else
            echo environment is 'develop'
            echo "environment=develop" >> $GITHUB_OUTPUT
            echo "image-suffix=dev" >> $GITHUB_OUTPUT
          fi
